name: 🐞 Bug report
description: Report a bug or an issue.
title: "bug: "
labels: ["Bug report"]
body:
  - type: markdown
    attributes:
      value: |
        <p align="center">
          <picture>
            <source
              width="256px"
              media="(prefers-color-scheme: dark)"
              srcset="https://raw.githubusercontent.com/revanced/revanced-patches-template/main/assets/revanced-headline/revanced-headline-vertical-dark.svg"
            >
            <img 
              width="256px"
              src="https://raw.githubusercontent.com/revanced/revanced-patches-template/main/assets/revanced-headline/revanced-headline-vertical-light.svg"
            >
          </picture>
          <br>
          <a href="https://revanced.app/">
             <picture>
                 <source height="24px" media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/revanced/revanced-patches-template/main/assets/revanced-logo/revanced-logo.svg" />
                 <img height="24px" src="https://raw.githubusercontent.com/revanced/revanced-patches-template/main/assets/revanced-logo/revanced-logo.svg" />
             </picture>
           </a>&nbsp;&nbsp;&nbsp;
           <a href="https://github.com/ReVanced">
               <picture>
                   <source height="24px" media="(prefers-color-scheme: dark)" srcset="https://i.ibb.co/dMMmCrW/Git-Hub-Mark.png" />
                   <img height="24px" src="https://i.ibb.co/9wV3HGF/Git-Hub-Mark-Light.png" />
               </picture>
           </a>&nbsp;&nbsp;&nbsp;
           <a href="http://revanced.app/discord">
               <picture>
                   <source height="24px" media="(prefers-color-scheme: dark)" srcset="https://user-images.githubusercontent.com/13122796/178032563-d4e084b7-244e-4358-af50-26bde6dd4996.png" />
                   <img height="24px" src="https://user-images.githubusercontent.com/13122796/178032563-d4e084b7-244e-4358-af50-26bde6dd4996.png" />
               </picture>
           </a>&nbsp;&nbsp;&nbsp;
           <a href="https://reddit.com/r/revancedapp">
               <picture>
                   <source height="24px" media="(prefers-color-scheme: dark)" srcset="https://user-images.githubusercontent.com/13122796/178032351-9d9d5619-8ef7-470a-9eec-2744ece54553.png" />
                   <img height="24px" src="https://user-images.githubusercontent.com/13122796/178032351-9d9d5619-8ef7-470a-9eec-2744ece54553.png" />
               </picture>
           </a>&nbsp;&nbsp;&nbsp;
           <a href="https://t.me/app_revanced">
              <picture>
                 <source height="24px" media="(prefers-color-scheme: dark)" srcset="https://user-images.githubusercontent.com/13122796/178032213-faf25ab8-0bc3-4a94-a730-b524c96df124.png" />
                 <img height="24px" src="https://user-images.githubusercontent.com/13122796/178032213-faf25ab8-0bc3-4a94-a730-b524c96df124.png" />
              </picture>
           </a>&nbsp;&nbsp;&nbsp;
           <a href="https://x.com/revancedapp">
              <picture>
                 <source media="(prefers-color-scheme: dark)" srcset="https://user-images.githubusercontent.com/93124920/270180600-7c1b38bf-889b-4d68-bd5e-b9d86f91421a.png">
                 <img height="24px" src="https://user-images.githubusercontent.com/93124920/270108715-d80743fa-b330-4809-b1e6-79fbdc60d09c.png" />
              </picture>
           </a>&nbsp;&nbsp;&nbsp;
           <a href="https://www.youtube.com/@ReVanced">
              <picture>
                 <source height="24px" media="(prefers-color-scheme: dark)" srcset="https://user-images.githubusercontent.com/13122796/178032714-c51c7492-0666-44ac-99c2-f003a695ab50.png" />
                 <img height="24px" src="https://user-images.githubusercontent.com/13122796/178032714-c51c7492-0666-44ac-99c2-f003a695ab50.png" />
             </picture>
           </a>
           <br>
           <br>
           Continuing the legacy of Vanced
        </p>

        # ReVanced Patches template bug report

        Before creating a new bug report, please keep the following in mind:

        - **Do not submit a duplicate bug report**: Search for existing bug reports [here](https://github.com/ReVanced/revanced-patches-template/issues?q=label%3A%22Bug+report%22).
        - **Review the contribution guidelines**: Make sure your bug report adheres to it. You can find the guidelines [here](https://github.com/ReVanced/revanced-patches-template/blob/main/CONTRIBUTING.md).
        - **Do not use the issue page for support**: If you need help or have questions, check out other platforms on [revanced.app](https://revanced.app).
  - type: textarea
    attributes:
      label: Bug description
      description: |
        - Describe your bug in detail
        - Add steps to reproduce the bug if possible (Step 1. ... Step 2. ...)
        - Add images and videos if possible
    validations:
      required: true
  - type: textarea
    attributes:
      label: Error logs
      description: Exceptions can be captured by running `logcat | grep AndroidRuntime` in a shell.
      render: shell
  - type: textarea
    attributes:
      label: Solution
      description: If applicable, add a possible solution to the bug.
  - type: textarea
    attributes:
      label: Additional context
      description: Add additional context here.
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your bug report will be closed if you don't follow the checklist below.
      options:
        - label: I have checked all open and closed bug reports and this is not a duplicate.
          required: true
        - label: I have chosen an appropriate title.
          required: true
        - label: All requested information has been provided properly.
          required: true
