name: ⭐ Feature request
description: Create a detailed request for a new feature.
title: 'feat: '
labels: ['Feature request']
body:
  - type: markdown
    attributes:
      value: |
        # ReVanced Patches feature request
        
        Please check for existing feature requests
        [here](https://github.com/ReVanced/revanced-patches/labels/Feature%20request)
        before creating a new one.
  - type: textarea
    attributes:
      label: Feature description
      description: |
        - Describe your feature in detail
        - Add images, videos, links, examples, references, etc. if possible
        - Add the target application name in case you request a new patch
  - type: textarea
    attributes:
      label: Motivation
      description: | 
        A strong motivation is necessary for a feature request to be considered.
        
        - Why should this feature be implemented? 
        - What is the explicit use case?
        - What are the benefits?
        - What makes this feature important?
    validations:
      required: true
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your issue will be closed if you don't follow the checklist below.
      options:
        - label: This request is not a duplicate of an existing issue.
          required: true
        - label: I have chosen an appropriate title.
          required: true
        - label: All requested information has been provided properly.
          required: true
