name: ⭐ Patch Request
description: Create a detailed patch request.
title: 'feat(patch): '
labels: [patch-request]
body:
  - type: textarea
    attributes:
      label: Application
      description: Which application is this patch for?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Issue
      description: What is the issue this patch should solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Patch
      description: "Describe the patch you'd like to see in detail."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Motivation
      description: Why should your patch request should be considered? What makes it valuable to the community?
    validations:
      required: true
