name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle
      - name: Setup Android SDK
        uses: amyu/setup-android@v2
        with:
          cache-disabled: false
          sdk-version: '33'
          build-tools-version: '33.0.3'
      - name: Build with Gradle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew generateMeta clean --no-daemon
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          path: build/libs/revanced-patches-*
