name: Update Gradle Wrapper

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          target-branch: dev
